//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_status
    {
        public int book_status_id { get; set; }
        public string book_status_code { get; set; }
        public string book_status_name { get; set; }
    }
}
