//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_order
    {
        public int book_order_id { get; set; }
        public int cus_id { get; set; }
        public float book_order_total { get; set; }
        public System.DateTime book_order_date { get; set; }
    }
}
