//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_order_detail
    {
        public int book_order_detail_id { get; set; }
        public int book_order_id { get; set; }
        public int book_product_id { get; set; }
        public float book_order_detail_price { get; set; }
        public int book_order_detail_qty { get; set; }
    }
}
