//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvc_projectEntities : DbContext
    {
        public mvc_projectEntities()
            : base("name=mvc_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book_category> book_category { get; set; }
        public virtual DbSet<book_order> book_order { get; set; }
        public virtual DbSet<book_order_detail> book_order_detail { get; set; }
        public virtual DbSet<book_product> book_product { get; set; }
        public virtual DbSet<book_status> book_status { get; set; }
        public virtual DbSet<book_type> book_type { get; set; }
        public virtual DbSet<customer> customer { get; set; }
    }
}
